# Generated by Django 3.2.21 on 2023-09-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_alter_transacao_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos',
            },
        ),
    ]
