# Generated by Django 3.2.21 on 2023-09-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_tipos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transações'},
        ),
    ]
