# Generated by Django 3.2.21 on 2023-09-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_alter_transacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.tipos'),
        ),
    ]
