# Generated by Django 3.2.21 on 2023-09-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_transacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='banco',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
